### ISSUE TITLE
Change Readme

### ISSUE THREAD

**Issue by ItsNash0** [useignition/Lazarus#1]
It does not protect against 7 Day certificates as the are not revoking, they are expiring, which you cant protect against.

**Comment by ASCEND1NG-VO1D** [comment]
Yes but 7-day certificates can be revoked earlier than 7 days, and you can use a 7-day certificate to block revokes to the enterprise and 7-day certificates

**Comment by useignition** [comment]
As stated about by @ASCEND1NG-VO1D a user can revoke a 7-day certificate in order to install more applications. The URLs blocks should in theory prevent the apps from not working after it gets revoked however it won't stop them from expiring.
